"""Update Enrollment: add term/year, remove status/progress

Revision ID: fac9c22faba2
Revises: 827c060b3ec1
Create Date: 2025-12-15 16:05:50.834590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fac9c22faba2'
down_revision = '827c060b3ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('term', sa.String(), nullable=True))
        batch_op.drop_column('status')
        batch_op.drop_column('progress')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('term')
        batch_op.drop_column('year')

    # ### end Alembic commands ###
